name: Bug Report
description: Report an issue with the system
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      placeholder: Describe what went wrong
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Run pipeline
        2. Process email
        3. Observe error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Security Impact (if any)
      placeholder: Does this bug affect confidentiality, integrity, or availability?
